version: '3.3'

services:
  proxy:
    image: nginx:1.12
    container_name: inz_proxy
    ports:
      - 80:80
    volumes:
      - ./volumes/web/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - front_end
      - back_end

  front_end:
    image: inzadrianbury/front-end:latest
    restart: always
    container_name: inz_front_end

  back_end:
    image: inzadrianbury/back-end:latest
    restart: always
    container_name: inz_back_end
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
    depends_on:
      - database

  database:
    image: mongo:3.7.1
    restart: always
    container_name: inz_database
    volumes:
      - ./volumes/database/config:/data/configdb
      - ./volumes/database/db:/data/db
